# openapi2-functions.yaml
swagger: '2.0'
info:
  title: movie-api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /random_movie:
    get:
      summary: valitse random leffa
      operationId: random_movie
      x-google-backend:
        address: https://us-central1-week9-2-334408.cloudfunctions.net/function-1-random-movie
      responses:
        '200':
          description: A successful response
          schema:
            type: string